set-threads:
  - convert_gfa_to_gbz=16
  - index_minimizer=16
  - index_r=16
  - index_haplotype_kmers=16
  - index_snarls=4
  - pack=8
  - vgcall=8
  - dv_make_examples=8
  - dv_call_variants=8
  - count_kmer_in_reads=16
  - map_short_reads_giraffe=16
  - sample_haplotypes=16
  - surject_reads=16
set-resources:
  - convert_gfa_to_gbz:mem=60GB
  - index_minimizer:mem=60GB
  - index_distance:mem=120GB
  - index_r:mem=60GB
  - index_haplotype_kmers:mem=60GB
  - index_snarls:mem=60GB
  - extract_ref_fasta:mem=20GB
  - index_fasta:mem=10GB
  - index_bam:mem=10GB
  - pack:mem=60GB
  - vgcall:mem=60GB
  - dv_make_examples:mem=60GB
  - dv_call_variants:mem=60GB
  - count_kmer_in_reads:mem=64GB
  - map_short_reads_giraffe:mem=64GB
  - sample_haplotypes:mem=64GB
  - surject_reads:mem=64GB
