jobs: 100
set-threads:
  - convert_gfa_to_gbz=16
  - index_minimizer=16
  - index_r=16
  - index_haplotype_kmers=16
  - index_snarls=4
  - pack=8
  - vgcall=8
  - dv_make_examples=8
  - dv_call_variants=8
  - count_kmer_in_reads=16
  - map_short_reads_giraffe=16
  - sample_haplotypes=16
  - surject_reads=16
set-resources:
  - convert_gfa_to_gbz:mem=60GB
  - index_minimizer:mem=120GB
  - index_distance:mem=120GB
  - index_r:mem=120GB
  - index_haplotype_kmers:mem=60GB
  - index_snarls:mem=60GB
  - extract_ref_fasta:mem=20GB
  - index_fasta:mem=10GB
  - index_bam:mem=10GB
  - pack:mem=80GB
  - vgcall:mem=80GB
  - dv_make_examples:mem=60GB
  - dv_call_variants:mem=60GB
  - count_kmer_in_reads:mem=64GB
  - map_short_reads_giraffe:mem=80GB
  - sample_haplotypes:mem=64GB
  - surject_reads:mem=80GB
  - convert_gfa_to_gbz:runtime=3h
  - index_minimizer:runtime=3h
  - index_distance:runtime=6h
  - index_r:runtime=3h
  - index_haplotype_kmers:runtime=3h
  - index_snarls:runtime=3h
  - extract_ref_fasta:runtime=1h
  - index_fasta:runtime=1h
  - index_bam:runtime=1h
  - pack:runtime=6h
  - vgcall:runtime=6h
  - dv_make_examples:runtime=12h
  - dv_call_variants:runtime=12h
  - count_kmer_in_reads:runtime=6h
  - map_short_reads_giraffe:runtime=12h
  - sample_haplotypes:runtime=6h
  - surject_reads:runtime=12h
