jobs: 20
set-threads:
  - convert_gfa_to_gbz=16
  - index_minimizer=8
  - index_r_fullpg=16
  - index_haplotype_kmers=16
  - index_snarls=4
  - pack=8
  - vgcall=4
  - dv_make_examples=12
  - dv_call_variants=12
  - dv_call_variants_gpu=12
  - count_kmer_in_reads=8
  - map_short_reads_giraffe=16
  - sample_haplotypes=8
  - surject_reads=24
  - surject_reads_tmp=24
  - prepare_target_regions=8
  - realign_bam=16
  - cram_to_fastq=4
  - trim_fastq=4
  - qc_fastq=6
  - qc_trimmed_fastq=6
  - sv_call_manta=8
  - coverage_mosdepth=4
set-resources:
  - convert_gfa_to_gbz:mem=60GB
  - convert_gfa_to_gbz:runtime=3h
  - index_minimizer:mem=64GB
  - index_minimizer:runtime=3h
  - index_distance_fullpg:mem=64GB
  - index_distance_fullpg:runtime=1h
  - index_distance:mem=64GB
  - index_distance:runtime=1h
  - index_r_fullpg:mem=60GB
  - index_r_fullpg:runtime=3h
  - index_haplotype_kmers:mem=60GB
  - index_haplotype_kmers:runtime=3h
  - index_snarls:mem=60GB
  - index_snarls:runtime=3h
  - extract_ref_fasta:mem=20GB
  - extract_ref_fasta:runtime=1h
  - index_fasta:mem=10GB
  - index_fasta:runtime=1h
  - index_bam:mem=4GB
  - index_bam:runtime=1h
  - index_bam_tmp:mem=4GB
  - index_bam_tmp:runtime=1h
  - pack:mem=64GB
  - pack:runtime=3h
  - vgcall:mem=120GB
  - vgcall:runtime=6h
  - dv_make_examples:mem=16GB
  - dv_make_examples:runtime=12h
  - dv_call_variants:mem=32GB
  - dv_call_variants:runtime=20h
  - dv_call_variants_gpu:mem=32GB
  - dv_call_variants_gpu:runtime=20h
  - dv_call_variants_gpu:slurm_extra=--partition=gpuq --gres=gpu:A100_1g.10gb:1
  - count_kmer_in_reads:mem=64GB
  - count_kmer_in_reads:runtime=1h
  - map_short_reads_giraffe:mem=64GB
  - map_short_reads_giraffe:runtime=6h
  - sample_haplotypes:mem=40GB
  - sample_haplotypes:runtime=1h
  - surject_reads:mem=32GB
  - surject_reads:runtime=24h
  - prepare_target_regions:mem=16GB
  - prepare_target_regions:runtime=3h
  - realign_bam:mem=32GB
  - realign_bam:runtime=24h
  - trim_fastq:mem=16GB
  - trim_fastq:runtime=6h
  - cram_to_fastq:mem=8GB
  - cram_to_fastq:runtime=12h
  - qc_fastq:mem=16GB
  - qc_fastq:runtime=12h
  - qc_trimmed_fastq:mem=16GB
  - qc_trimmed_fastq:runtime=12h
  - sv_call_manta:mem=32GB
  - sv_call_manta:runtime=12h
  - coverage_mosdepth:mem=16GB
  - coverage_mosdepth:runtime=12h
